plugins {
    id 'buildlogic.java-conventions'
}

description = '117 HD Plugin'

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

dependencies {
    api project(':runelite-api')
    api project(':client')
    compileOnly libs.org.projectlombok.lombok
    annotationProcessor libs.org.projectlombok.lombok
    compileOnly libs.com.google.code.findbugs.jsr305
    compileOnly libs.org.jetbrains.annotations
    api libs.com.google.code.gson.gson
    api libs.com.google.inject.guice
    api libs.org.lwjgl.lwjgl
    api libs.org.lwjgl.lwjgl.opengl
    api libs.org.lwjgl.lwjgl.opencl
    runtimeOnly libs.org.lwjgl.lwjgl
        runtimeOnly(variantOf(libs.org.lwjgl.lwjgl) { classifier("natives-windows") })
        runtimeOnly(variantOf(libs.org.lwjgl.lwjgl) { classifier("natives-windows-x86") })
        runtimeOnly(variantOf(libs.org.lwjgl.lwjgl) { classifier("natives-windows-arm64") })
    runtimeOnly libs.org.lwjgl.lwjgl.opengl
        runtimeOnly(variantOf(libs.org.lwjgl.lwjgl.opengl) { classifier("natives-windows") })
        runtimeOnly(variantOf(libs.org.lwjgl.lwjgl.opengl) { classifier("natives-windows-x86") })
        runtimeOnly(variantOf(libs.org.lwjgl.lwjgl.opengl) { classifier("natives-windows-arm64") })
}
